name: pgs_edupro
description: A new Learning Platform.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.1.0+36

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  fluttertoast: ^8.1.2
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  dartz: ^0.10.1
  kt_dart: ^1.0.0
  uuid: ^3.0.7
  get: ^4.6.5
  get_it: ^7.2.0
  injectable: ^2.1.0
  package_info_plus: ^1.3.0
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  another_flushbar: ^1.12.29
  flutter_hooks: ^0.18.5+1
  styled_widget: ^0.4.1
  time: ^2.1.3
  cached_network_image: ^3.2.3
  toggle_switch: ^2.0.1
  razorpay_flutter: ^1.3.2
  visibility_detector: ^0.3.3
  path_provider: ^2.0.11
  youtube_player_flutter: ^8.1.1
  flutter_web_browser: ^0.17.1
  url_launcher: ^6.1.7
  bottom_navy_bar: ^6.0.0
  date_field: ^3.0.2
  image_picker: ^0.8.6
  contained_tab_bar_view: ^0.8.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  connection_notifier: ^1.0.1
  animated_text_kit: ^4.2.2
  flutter_html: ^2.2.1
  expansion_tile_card: ^2.0.0
  animate_gradient: ^0.0.2
  percent_indicator: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash/splash.png"
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash/ 
    - assets/images/
    - assets/images/home/
    - assets/icons/
    - assets/icons/drawer_icons/
    - assets/icons/profile_icons/
    - assets/icons/navigation_icons/
    - assets/icons/register_icons/
    - assets/gif/loaders/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/Sigmar-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
